### ISSUE TITLE
ACPI: from_tables_direct has been removed

### ISSUE THREAD

**Issue by rw-vanc** [rust-osdev/acpi#172]
What is the recommended alternative to acpi::AcpiTables::from_tables_direct, which has been removed? My ideal would be to pass in the tables without a handler to map the table data, but I'm not sure how much you need to access tables using physical addresses.

I'm happy to implement whatever you think the best solution is.

**Comment by rw-van** [comment]
From Isaac:

So `from_tables_direct` was removed when we moved away from pre-processing all of the tables into a container, and isn't easily re-added unfortunately. However, we should still be able to use all the types (only the new functions tend to be parameterized over the Handler, so we could provide a new way to construct tables without a handler fairly easily I think, depending on what exactly you want on your end

**Comment by rw-van** [comment]
Just to be clear, the proposed solution is to change parameterized types for the various tables to not be parameterized, but to leave a parameterized `new` function that takes a Handler, and a different non-parameterized version that is created from contiguous table data possibly in virtual memory. This will be a breaking change due to the removal of the type parameter.

**Comment by onkoe** [comment]
`from_tables_direct` is still mentioned in the `acpi` crate's module documentation.

**Comment by IsaacWoods** [comment]
> `from_tables_direct` is still mentioned in the `acpi` crate's module documentation.

Thanks for reporting, I've removed the reference to this method from the documentation.
