### ISSUE TITLE
More things must be `unsafe` 

### ISSUE THREAD

**Issue by Restioson** [rust-osdev/acpi#25]
Quite a few methods that are currently safe should really be unsafe. For instance, `AcpiHandler` methods (I will attempt to address this as I wish to try streamline its api), and methods that map physical memory (perhaps, better safe than sorry).

**Comment by MikailBag** [comment]
To my mind, `parse_rsdt` and `parse_rsdp` should be unsafe too, because they read from caller-provided physical address, which can break aliasing or memory-mapped IO

**Comment by IsaacWoods** [comment]
Yep, you're both right. Specifially, these are the methods that I think need to be changed to unsafe:
* `parse_rsdt`
* `parse_rsdp` (but not `parse_validated_rsdp` since it takes a mapping directly)
* `AcpiHandler::map_physical_region`
* **not** `AcpiHandler::unmap_physical_region` - as long as we don't go constructing random `PhysicalMapping`s from **within the library** this is safe, and so I think that's a bit defensive

I also think I missed a requirement of `map_physical_region` when I wrote up its documentation, that `physical_address` (and so the resulting virtual address it's mapped to) must be aligned to `T`'s alignment requirement.

I would accept a PR making these changes (making the documentation change would be great even if it's not directly connected to the unsafe issue), but won't have time to work on this for quite a while myself.
