### ISSUE TITLE
Redox has an acpi and aml implementation

### ISSUE THREAD

**Issue by lachlansneff** [rust-osdev/acpi#7]
By the way, redox os has a (presumably) correct implementation of acpi and aml interpretation, so you can probably just ask for @jackpot51 to put that in a separate repository or take inspiration from that.

https://github.com/redox-os/kernel/tree/master/src/acpi

**Comment by IsaacWoods** [comment]
Yeah, Redox's ACPI implementation is really impressive! From what I can see though:
* It would require not-minor changes to how Redox is laid out to be OS agnostic. Look [here](https://github.com/redox-os/kernel/blob/master/src/acpi/madt.rs#L100-L110) for an example in the MADT initialisation to see how it can be fairly Redox-specific. A goal of `acpi` is to be easy to integrate into a kernel if you've decided you don't care about ACPI.
* Redox does not contain any ACPI regression testing. It is "(presumably) correct". A stretch goal for `acpi` is to be able to automatically test against as many hardware platforms as we can find.
* I'd like to get myself (and hopefully at least a few contributors) relatively familiar with ACPI so we have a good enough understanding to maintain and extend the library. Starting with a relatively complete implementation kind of doesn't allow this
* I don't know enough about software licenses to be sure we could use code from Redox (licensed under just MIT I think within a dual MIT/Apache repo)

Of course, if @jackpot51 or someone/people in Redox want to make their ACPI implementation more generalised, then it'd probably make this obsolete because of how much of a head-start they've got, but I can't see the advantage in that for them. I don't want this to sound not-invented-here-y, so just shout if it does, but that's my thought process.
