### ISSUE TITLE
Example with x86_64 crate?

### ISSUE THREAD

**Issue by Luis-Hebendanz** [rust-osdev/acpi#78]
Hello!

I tried to use this library but miserably failed to do so while battling with the rust compiler. 
Could you add a little example while using the x86_64 crates FrameAllocator & OffsetPageTable? 
I would deeply appreciate it :)
 I tried using a struct like this:
```rust
#[derive(Clone)]
pub struct MyAcpiHandler<'a> {
    mapper: Rc<RefCell<&'a mut OffsetPageTable<'a>>>,
    frame_allocator: Rc<RefCell<&'a mut dyn FrameAllocator<Size4KiB>>>,
}
```
but this failed with the error:
```rust
.map_to(page, frame, flags, self.frame_allocator.get_mut())
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `FrameAllocator<Size4KiB>` is not implemented for `&mut dyn FrameAllocator<Size4KiB>`
```

**Comment by Restioson** [comment]
This seems like an x86_64 issue since acpi has no `FrameAllocator` trait

**Comment by phil-opp** [comment]
> Maybe this could be relaxed though.

Yeah, I think we can relax this. I opened https://github.com/rust-osdev/x86_64/pull/204 for this.

**Comment by IsaacWoods** [comment]
Hi, always nice to hear of people using the library! I'm afraid I don't have much experience with the `x86_64` crate as my kernel doesn't use it. Those types are pretty complicated though, it might be worth making `MyAcpiHandler` generic over the type of `FrameAllocator` instead of using a trait object (you'll probably only be monomorphising one copy of the code anyway).

EDIT: ah looks like Phil's on it :) hope you get this working @Luis-Hebendanz!

**Comment by Luis-Hebendanz** [comment]
Damn you guys are fast! Thanks for the help :D

**Comment by Luis-Hebendanz** [comment]
Hmm @phil-opp I tried your pull request out in the x86_64 crate but I still get the error:
```rust
.map_to(page, frame, flags, self.frame_allocator.get_mut())
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `FrameAllocator<Size4KiB>` is not implemented for `&mut dyn FrameAllocator<Size4KiB>`
```
If I try to de reference it fails with:
```rust
   --> src/apic.rs:192:29
    |
192 |           let map_to_result = self
    |  _____________________________^
193 | |             .mapper
    | |___________________^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<RefCell<&mut OffsetPageTable<'_>>>`

error[E0596]: cannot borrow data in an `Rc` as mutable
   --> src/apic.rs:195:42
    |
195 |             .map_to(page, frame, flags, *self.frame_allocator.get_mut())
    |                                          ^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<RefCell<&mut dyn FrameAllocator<Size4KiB>>>`
```
I think my approach is incorrect but how could this be done then?

**Comment by phil-opp** [comment]
Try using [`borrow_mut`](https://doc.rust-lang.org/stable/std/cell/struct.RefCell.html#method.borrow_mut) instead of [`get_mut`](https://doc.rust-lang.org/stable/std/cell/struct.RefCell.html#method.get_mut). The latter requires a `&mut` reference to the `RefCell` which is not possible for `Rc<RefCell<_>>`.

**Comment by Luis-Hebendanz** [comment]
Wow it worked. I have no idea why but it worked! Now I have to sit down and find out why and how :)

**Comment by phil-opp** [comment]
Let me try to explain this in a bit more detail:

The last error had nothing to do with the `x86_64` crate (it was just masked by the earlier error). The error also occurs when you try `self.frame_allocator.get_mut()` independently.

When you use the `borrow_mut()` method you get a mutable reference to the type wrapped in `RefCell`, which is `&mut dyn FrameAllocator<Size4KiB>` in your case. So the resulting type is `&mut &mut dyn FrameAllocator<Size4KiB>`. To remove the double reference, you need to dereference once.

All generic parameters in Rust have an implicit `Sized` bound by default. This means that the size of the parameter needs to be known at compile time. Since the `map_to` method takes only references to the `FrameAllocator` as argument, this implicit bound isn't needed, so we can opt-out using the `?Sized` bound (that's what the linked PR does). This way, the dynamically-sized `dyn FrameAllocator` type is now usable with the method.

I hope this makes things clearer!

**Comment by Luis-Hebendanz** [comment]
You are awesome!
