### ISSUE TITLE
Cannot access to `Signature` type

### ISSUE THREAD

**Issue by toku-sa-n** [rust-osdev/acpi#82]
Sorry if I missed something, but we cannot access to `Signature` type because the module `sdt` is private. Is it intentional? If so, how to use methods like `AcpiTables::get_sdt` which takes `Signature` value?

**Comment by IsaacWoods** [comment]
This just looks like an oversight, sorry! I've published `v2.1.0` which makes the `sdt` module public.

Was this just something you noticed, or do you need to manually parse a table that we don't support - if it's one of the standard tables, it'd be cool to add it to the library instead of you having to access it raw :)

**Comment by toku-sa-n** [comment]
Thank you. I was trying to handle the APIC, but after posting this issue, I noticed that I could access it via `AcpiTables::platform_info`.
